language: go
sudo: false

go:
  - 1.8.x
  - 1.9.x

install:
  - go version
  - export PATH="$PATH:$GOPATH/bin"
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/goimports

script:
  - go run build.go -v
  - go test 
  - diff <(goimports -d *.go) <(printf "")
  - diff <(golint *.go) <(printf "")

after_success:
  - diff <(golint *.go) <(rintf "")
