language: go
sudo: false

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"

install:
  - go version
  - export PATH="$PATH:$GOPATH/bin"
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/goimports

script:
  - go run build.go --goos linux
  - go run build.go --goos windows
  - go run build.go --goos darwin
  - go test $(go list ./... | grep -v /vendor/)
  - diff <(goimports -d *.go */*.go */*/*.go) <(printf "")
  - diff <(golint *.go */*.go */*/*.go) <(printf "")

after_success:
  - diff <(golint *.go */*.go */*/*.go) <(printf "")
