name: Style Checkers
on: [push]
jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run golang-ci
        uses: actions-contrib/golangci-lint@v1
        with:
          args: run --enable goimports,govet,misspell,stylecheck
