name: Run unit tests
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version:
          - 1.11.x
          - 1.12.x
          - 1.13.x
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Get programs
        run: |
          export GOBIN=$HOME/bin
          export PATH=$PATH:$HOME/bin
          go get golang.org/x/lint/golint
          go get golang.org/x/tools/cmd/goimports

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: |
          go run -mod=vendor build.go --goos linux
          go run -mod=vendor build.go --goos windows
          go run -mod=vendor build.go --goos darwin

      - name: Run tests
        run: |
          go env
          echo $PATH
          go test -mod=vendor ./...
          diff <(goimports -d *.go */*.go */*/*.go) <(printf "")
          diff <(golint *.go */*.go */*/*.go) <(printf "")
